--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ACM-PocketMine-MP/EconomyAPI
build-by-default: true
branches:
- main
projects:
  EconomyAPI:
    path: ""
    lint:
      phpstan: false
...
