---
name: EconomyAPI
main: onebone\economyapi\EconomyAPI
api: 5.0.0
version: 6.0.0-PM5
author: [fernanACM, onebone]
permissions:
  economyapi.command.setmoney:
    default: op
    description: Allows to set player's money
  economyapi.command.mymoney:
    description: Allows player to see his/her money
    default: true
  economyapi.command.givemoney:
    description: Allows player to give money to others
    default: op
  economyapi.command.pay:
    description: Allows player to pay to someone
    default: true
  economyapi.command.seemoney:
    description: Allows player to see others' money
    default: true
  economyapi.command.setlang:
    description: Allows player to set his/her language
    default: true
  economyapi.command.topmoney:
    description: Allows player to see top money list
    default: true
  economyapi.command.mystatus:
    description: Allows player to see his/her financial status
    default: true
  economyapi.command.takemoney:
    description: Allows player to take money from others
    default: op
...
